<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESK-20180722NA" ignored="0" name="我的页面" tests="2" failures="2" timestamp="20 Aug 2021 06:30:07 GMT" time="6.953" errors="0">
  <testcase name="pwdFast" time="0.133" classname="hlife.test.integration.Fast">
    <failure type="java.lang.AssertionError" message="验证码登录接口访问失败 expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: 验证码登录接口访问失败 expected [1] but found [0]
at hlife.test.integration.Fast.pwdFast(Fast.java:137)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- pwdFast -->
  <testcase name="verifyFast" time="0.159" classname="hlife.test.integration.Fast">
    <failure type="java.lang.AssertionError" message="验证码登录接口访问失败 expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: 验证码登录接口访问失败 expected [1] but found [0]
at hlife.test.integration.Fast.verifyFast(Fast.java:50)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- verifyFast -->
</testsuite> <!-- 我的页面 -->
